version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    env_file: .env
  server:
    build:
      context: ./packages/server
      dockerfile: ./dockerfile
    volumes:
      - ./packages/server/dist:/server/dist
      - ./packages/server/package.json:/server/package.json
    env_file: .env
    entrypoint: ['tail', '-f', '/dev/null']
