version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    env_file: .env
  server:
    build:
      context: ./packages/server
      dockerfile: ./dockerfile
    working_dir: /server
    volumes:
      - ./packages/server/lib:/server/lib
      - ./packages/server/package.json:/server/package.json
      - lyi-sdk-server-vol:/server/node_modules
    env_file: .env
    ports:
      - 3000-3005:3000-3005
    entrypoint: ['tail', '-f', '/dev/null']
volumes:
  lyi-sdk-server-vol: